// Explicit content metadata. Resource names are identifiers, never runtime behavior rules.
export type AssetProfile = {
  roughness?: number;
  metalness?: number;
  envMapIntensity?: number;
  material: "standard" | "block" | "lens" | "badge";
  lamp?: "post" | "box";
  ground: boolean;
  mineBatch: boolean;
  fixed: boolean;
  collision: "none" | "hut" | "small" | "tree" | "cart";
};
export const ASSET_PROFILES: Readonly<Record<string, AssetProfile>> = {
  "anvil-stump": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "assayer-stall": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "hut",
  },
  "bank-braced": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "bank-fence": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "bank-timber": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "bank-turf": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "barrel-pair": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "bench-timber": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "birch-round": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "boulder-moss": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "boulder-ore": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "cart-empty": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "cedar-pillow": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "crate-stack": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "crown-tree": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "egg-core-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "egg-crystal-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "egg-ember-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "egg-meadow-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "egg-moon-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "egg-tide-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "fence-corner": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "flower-daisies": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "grass-tussock": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "grid-mine-roof-blender": {
    material: "standard",
    ground: false,
    mineBatch: true,
    fixed: true,
    collision: "none",
  },
  "grid-mine-timber-blender": {
    material: "standard",
    ground: false,
    mineBatch: true,
    fixed: true,
    collision: "none",
  },
  "grid-mine-trim-blender": {
    material: "standard",
    ground: false,
    mineBatch: true,
    fixed: true,
    collision: "none",
  },
  "lantern-post": {
    material: "standard",
    lamp: "post",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "maple-coral": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "maple-gold": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "meadow-base": {
    material: "standard",
    ground: true,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "mine-badge": {
    material: "badge",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "mine-fence": {
    material: "block",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "mine-pendant": {
    material: "lens",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "mushroom-cluster": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "notice-board": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "oak-tall": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "oak-wide": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  "ore-bin-copper": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "ore-bin-jade": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "ore-cart": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "cart",
  },
  "pit-box-lantern": {
    material: "standard",
    lamp: "box",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-crates": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-headframe": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-lumber-stack": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-plank-deck": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-sorting-table": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-spoil": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-supply-pallet": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-tool-wall": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-track": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "pit-winch": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "portal-core": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-crystal": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-fossil": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-frozen": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-fungal": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-plinth-blender": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-timber": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "portal-volcanic": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "rail-buffer": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "sack-stack": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "sapling-pair": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "shrub-berry": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "shrub-flower": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "shrub-round": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "simulator-exchange": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "simulator-upgrade": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: true,
    collision: "none",
  },
  "soft-shrub": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "supply-awning": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "hut",
  },
  "terrain-slab": {
    material: "standard",
    ground: true,
    mineBatch: false,
    fixed: false,
    collision: "none",
  },
  "tool-rack": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "warehouse-shed": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "hut",
  },
  "waystone-crystal": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "well-stone": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  wheelbarrow: {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "willow-dome": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "tree",
  },
  workbench: {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "small",
  },
  "workshop-hut": {
    material: "standard",
    ground: false,
    mineBatch: false,
    fixed: false,
    collision: "hut",
  },
};
export function assetProfile(id: string) {
  const profile = ASSET_PROFILES[id];
  if (!profile) throw Error("Missing asset profile: " + id);
  return profile;
}
