// Presentation only. Logic/catalog/save data never import this file.
export type PetAppearance = Readonly<{ color: string; label: string; radius: number }>;
export const PET_APPEARANCES: Readonly<Record<string, PetAppearance>> = {
  'moss-slime': { color: '#7ecf69', label: '苔团', radius: 0.42 },
  'quarry-mole': { color: '#bc986a', label: '鼠', radius: 0.44 },
  'amber-fox': { color: '#eca341', label: '狐', radius: 0.46 },
  'crystal-owl': { color: '#8bcbdc', label: '鹰', radius: 0.48 },
  'moon-dragon': { color: '#b2a0ee', label: '龙', radius: 0.52 },
  'pebble-blob': { color: '#ad9b83', label: '石团', radius: 0.42 },
  'pebble-scout': { color: '#9f946e', label: '砂鼠', radius: 0.44 },
  'pebble-friend': { color: '#b3988c', label: '兔', radius: 0.46 },
  'pebble-wing': { color: '#c1c1a2', label: '龟', radius: 0.48 },
  'pebble-guardian': { color: '#a57e77', label: '熊', radius: 0.52 },
  'copper-blob': { color: '#dd9658', label: '铜团', radius: 0.42 },
  'copper-scout': { color: '#d7a43a', label: '鼠', radius: 0.44 },
  'copper-friend': { color: '#e07d65', label: '狐', radius: 0.46 },
  'copper-wing': { color: '#e6da82', label: '鸟', radius: 0.48 },
  'copper-guardian': { color: '#da4e47', label: '牛', radius: 0.52 },
  'amber-blob': { color: '#eeb74c', label: '蜜团', radius: 0.42 },
  'amber-scout': { color: '#ebd22b', label: '蜂', radius: 0.44 },
  'amber-friend': { color: '#ef945a', label: '兔', radius: 0.46 },
  'amber-wing': { color: '#e9f27b', label: '蝶', radius: 0.48 },
  'amber-guardian': { color: '#ec6439', label: '狮', radius: 0.52 },
  'tide-blob': { color: '#54c5de', label: '水团', radius: 0.42 },
  'tide-scout': { color: '#3699d8', label: '鱼', radius: 0.44 },
  'tide-friend': { color: '#61e0d5', label: '蟹', radius: 0.46 },
  'tide-wing': { color: '#7fa8e6', label: '鲸', radius: 0.48 },
  'tide-guardian': { color: '#43dbb6', label: '龙', radius: 0.52 },
  'fire-blob': { color: '#fa874b', label: '火团', radius: 0.42 },
  'fire-scout': { color: '#f99c28', label: '鼠', radius: 0.44 },
  'fire-friend': { color: '#fa665a', label: '狐', radius: 0.46 },
  'fire-wing': { color: '#fbdd7d', label: '鸟', radius: 0.48 },
  'fire-guardian': { color: '#f93746', label: '龙', radius: 0.52 },
  'mushroom-blob': { color: '#cf7fbd', label: '菇团', radius: 0.42 },
  'mushroom-scout': { color: '#c5659b', label: '鼠', radius: 0.44 },
  'mushroom-friend': { color: '#d08ad3', label: '兔', radius: 0.46 },
  'mushroom-wing': { color: '#dda4b8', label: '蛙', radius: 0.48 },
  'mushroom-guardian': { color: '#b870c9', label: '鹿', radius: 0.52 },
  'silver-blob': { color: '#b2c7dc', label: '银团', radius: 0.42 },
  'silver-scout': { color: '#9dacd2', label: '鼠', radius: 0.44 },
  'silver-friend': { color: '#b2d2dc', label: '兔', radius: 0.46 },
  'silver-wing': { color: '#b2b5dc', label: '鹰', radius: 0.48 },
  'silver-guardian': { color: '#a7d3d7', label: '鹿', radius: 0.52 },
  'crystal-blob': { color: '#a38af2', label: '晶团', radius: 0.42 },
  'crystal-scout': { color: '#a66aee', label: '虫', radius: 0.44 },
  'crystal-friend': { color: '#989af4', label: '狐', radius: 0.46 },
  'crystal-wing': { color: '#d59af4', label: '鹤', radius: 0.48 },
  'crystal-guardian': { color: '#788df0', label: '龙', radius: 0.52 },
  'frost-blob': { color: '#93e0ef', label: '雪团', radius: 0.42 },
  'frost-scout': { color: '#74beea', label: '鼠', radius: 0.44 },
  'frost-friend': { color: '#9df1e8', label: '兔', radius: 0.46 },
  'frost-wing': { color: '#9dc0f1', label: '鹰', radius: 0.48 },
  'frost-guardian': { color: '#81ecd1', label: '熊', radius: 0.52 },
  'jade-blob': { color: '#55c995', label: '翠团', radius: 0.42 },
  'jade-scout': { color: '#3cbe9f', label: '虫', radius: 0.44 },
  'jade-friend': { color: '#61cd7f', label: '狐', radius: 0.46 },
  'jade-wing': { color: '#7cd5d3', label: '雀', radius: 0.48 },
  'jade-guardian': { color: '#46c456', label: '鹿', radius: 0.52 },
  'moon-blob': { color: '#af9cf1', label: '月团', radius: 0.42 },
  'moon-scout': { color: '#b082ee', label: '兔', radius: 0.44 },
  'moon-friend': { color: '#9ca0f1', label: '猫', radius: 0.46 },
  'moon-wing': { color: '#d39cf1', label: '枭', radius: 0.48 },
  'moon-guardian': { color: '#8fa2f0', label: '龙', radius: 0.52 },
  'ruin-blob': { color: '#c9b879', label: '砂团', radius: 0.42 },
  'ruin-scout': { color: '#bfbf60', label: '鼠', radius: 0.44 },
  'ruin-friend': { color: '#cdaa84', label: '猫', radius: 0.46 },
  'ruin-wing': { color: '#ccd89d', label: '鹰', radius: 0.48 },
  'ruin-guardian': { color: '#c38b6a', label: '兽', radius: 0.52 },
  'lava-blob': { color: '#ef6c52', label: '熔团', radius: 0.42 },
  'lava-scout': { color: '#ec7731', label: '虫', radius: 0.44 },
  'lava-friend': { color: '#f0606f', label: '蜥', radius: 0.46 },
  'lava-wing': { color: '#f3c481', label: '蝠', radius: 0.48 },
  'lava-guardian': { color: '#ed3f6c', label: '龙', radius: 0.52 },
  'fossil-blob': { color: '#d1b59a', label: '骨团', radius: 0.42 },
  'fossil-scout': { color: '#c6b181', label: '鼠', radius: 0.44 },
  'fossil-friend': { color: '#d6afa5', label: '龟', radius: 0.46 },
  'fossil-wing': { color: '#dcd8b2', label: '鸟', radius: 0.48 },
  'fossil-guardian': { color: '#cb908c', label: '龙', radius: 0.52 },
  'gear-blob': { color: '#7fb9c5', label: '铁团', radius: 0.42 },
  'gear-scout': { color: '#669aba', label: '鼠', radius: 0.44 },
  'gear-friend': { color: '#8acac3', label: '猫', radius: 0.46 },
  'gear-wing': { color: '#a2b7d5', label: '鹰', radius: 0.48 },
  'gear-guardian': { color: '#71bfab', label: '熊', radius: 0.52 },
  'star-blob': { color: '#9697ee', label: '星团', radius: 0.42 },
  'star-scout': { color: '#8e77e9', label: '兔', radius: 0.44 },
  'star-friend': { color: '#9eb5ef', label: '狐', radius: 0.46 },
  'star-wing': { color: '#c09eef', label: '鲸', radius: 0.48 },
  'star-guardian': { color: '#84b1eb', label: '龙', radius: 0.52 },
  'core-blob': { color: '#f1c957', label: '核团', radius: 0.42 },
  'core-scout': { color: '#eee536', label: '虫', radius: 0.44 },
  'core-friend': { color: '#f2a765', label: '狮', radius: 0.46 },
  'core-wing': { color: '#e3f586', label: '凰', radius: 0.48 },
  'core-guardian': { color: '#ef7b44', label: '龙', radius: 0.52 },
};
export function petAppearance(speciesId: string): PetAppearance {
  const appearance = PET_APPEARANCES[speciesId];
  if (!appearance) throw Error(`缺少宠物外观: ${speciesId}`);
  return appearance;
}
// Rows describe physical terraces only, never prices or stat multipliers.
export const EGG_DISPLAY_ROWS = [
  [
    { eggId: 'meadow-egg', asset: 'egg-meadow-blender', color: '#7ecf69' },
    { eggId: 'pebble-egg', asset: 'egg-core-blender', color: '#ad9b83' },
    { eggId: 'copper-egg', asset: 'egg-ember-blender', color: '#dd9658' },
    { eggId: 'amber-egg', asset: 'egg-moon-blender', color: '#eeb74c' },
    { eggId: 'tide-egg', asset: 'egg-tide-blender', color: '#54c5de' },
    { eggId: 'fire-egg', asset: 'egg-ember-blender', color: '#fa874b' },
  ],
  [
    { eggId: 'mushroom-egg', asset: 'egg-meadow-blender', color: '#cf7fbd' },
    { eggId: 'silver-egg', asset: 'egg-moon-blender', color: '#b5c9dd' },
    { eggId: 'crystal-egg', asset: 'egg-crystal-blender', color: '#a38af2' },
    { eggId: 'frost-egg', asset: 'egg-tide-blender', color: '#93e0ef' },
    { eggId: 'jade-egg', asset: 'egg-meadow-blender', color: '#55c995' },
    { eggId: 'moon-egg', asset: 'egg-moon-blender', color: '#b3a1f2' },
  ],
  [
    { eggId: 'ruin-egg', asset: 'egg-core-blender', color: '#c9b879' },
    { eggId: 'lava-egg', asset: 'egg-ember-blender', color: '#ef6c52' },
    { eggId: 'fossil-egg', asset: 'egg-core-blender', color: '#d1b59a' },
    { eggId: 'gear-egg', asset: 'egg-crystal-blender', color: '#7fb9c5' },
    { eggId: 'star-egg', asset: 'egg-moon-blender', color: '#9697ee' },
    { eggId: 'core-egg', asset: 'egg-core-blender', color: '#f1c957' },
  ],
] as const;
