import type { Solid } from './sceneryKit.ts';
export const WORKSITE_ASSETS=['pit-plank-deck','mine-fence','pit-headframe','pit-winch','pit-lumber-stack','pit-tool-wall','pit-sorting-table','pit-crates','pit-track','pit-spoil','pit-supply-pallet','pit-box-lantern'] as const;
type WorksitePlacement={asset:typeof WORKSITE_ASSETS[number];x:number;z:number;width:number;depth:number;height:number;yaw?:number;y?:number};
// All render geometry is generated by Tripo. These are assembly transforms only.
export const WORKSITE_PLACEMENTS:readonly WorksitePlacement[]=[
 ...[-5.4,5.4].map(x=>({asset:'pit-plank-deck' as const,x,z:-9.6,width:10.8,depth:2.4,height:.12,y:.02})),
 ...[-6.95,6.95].map(x=>({asset:'pit-plank-deck' as const,x,z:9.6,width:7.8,depth:2.4,height:.12,y:.02})),
 ...[-9.6,9.6].flatMap(x=>[-4.2,4.2].map(z=>({asset:'pit-plank-deck' as const,x,z,width:8.7,depth:2.4,height:.12,y:.014,yaw:Math.PI/2}))),
 // Low two-rail panels just outside the shaft. Four-metre front opening.
 ...[-8.9,8.9].flatMap(x=>[-6.675,-2.225,2.225,6.675].map(z=>({asset:'mine-fence' as const,x,z,width:4.45,depth:.28,height:1.05,y:.11,yaw:Math.PI/2}))),
 ...[-6.675,-2.225,2.225,6.675].map(x=>({asset:'mine-fence' as const,x,z:-8.9,width:4.45,depth:.28,height:1.05,y:.11})),
 ...[-7.2,-3.8,3.8,7.2].map(x=>({asset:'mine-fence' as const,x,z:8.9,width:3.4,depth:.28,height:1.05,y:.11})),
 {asset:'pit-headframe',x:14.5,z:-17.5,width:4.5,depth:3.3,height:6.2,yaw:-.15},
 {asset:'pit-winch',x:13,z:-6.8,width:2.8,depth:1.8,height:1.7,yaw:-Math.PI/2},
 {asset:'pit-lumber-stack',x:-15.5,z:-5.5,width:4,depth:1.7,height:1.1,yaw:Math.PI/2},
 {asset:'pit-lumber-stack',x:19,z:-17.5,width:3.5,depth:1.7,height:.9},
 {asset:'pit-tool-wall',x:-12.7,z:-.5,width:3.5,depth:.7,height:2.6,yaw:Math.PI/2},
 {asset:'pit-sorting-table',x:13,z:3,width:3.3,depth:1.5,height:1.3,yaw:-Math.PI/2},
 {asset:'pit-crates',x:-13.4,z:5,width:2.4,depth:2,height:1.6},
 {asset:'pit-crates',x:15.5,z:5,width:2.3,depth:1.8,height:1.5,yaw:.15},
 ...[-10.5,-5.5,-.5].map(z=>({asset:'pit-track' as const,x:-18,z,width:5.1,depth:1.5,height:.13,yaw:Math.PI/2})),
 {asset:'pit-spoil',x:14.5,z:-1,width:3.3,depth:2.3,height:.9},
 {asset:'pit-spoil',x:-14,z:-10.5,width:3,depth:2.2,height:.8},
 {asset:'pit-supply-pallet',x:-12,z:-14,width:2.6,depth:1.9,height:1.2},
 {asset:'pit-box-lantern',x:-14,z:12,width:.65,depth:.65,height:2.7},
 {asset:'pit-box-lantern',x:14,z:13,width:.65,depth:.65,height:2.7},
 {asset:'pit-box-lantern',x:-13.8,z:-13.8,width:.65,depth:.65,height:2.7},
];
// Collision remains separate from visual topology and voxel collision.
export const WORKSITE_SOLIDS:Solid[]=WORKSITE_PLACEMENTS.filter(p=>p.asset!=='pit-track').map(p=>({
 at:[p.x,(p.y??-.08)+p.height/2,p.z],
 half:[p.width*.48,p.height/2,p.depth*.48],yaw:p.yaw??0,
}));
