const style='An isolated modern ROBLOX Mining Simulator game prop. Extremely simple chunky voxel-like large shapes, clean saturated flat painted colors, matte nonmetal materials, no realistic grain, no tiny detail, no text, no logos, no characters, no ground landscape. Complete object, centered. ';
export const surfaceHub={
 'portal-timber':{faceLimit:1200,prompt:style+'Miniature old mine landmark: a squat square timber tunnel frame on a small flat stone foot, two fat straight oak pillars and a straight crossbeam, two large coal chunks beside it. Front faces open. Warm amber wood and dark slate. Width equals height.'},
 'portal-fungal':{faceLimit:1200,prompt:style+'Miniature mushroom cave landmark: exactly three large chunky glowing-looking turquoise and violet mushrooms on a small flat dark stone foot. Big smooth caps, short thick stems, no small mushrooms or grass. Simple iconic silhouette.'},
 'portal-crystal':{faceLimit:1200,prompt:style+'Miniature crystal cave landmark: three large faceted blue and lavender crystals rising from a small flat midnight-blue stone foot, broad simple polygon faces, cyan colored tips, no transparency, no tiny shards.'},
 'portal-ruins':{faceLimit:1400,prompt:style+'Miniature buried ruins landmark: two blocky cream sandstone columns supporting a lintel with a large turquoise square gem in the centre. Small flat stone foot, broken stepped top, simple block construction, no carvings or text.'},
 'portal-frozen':{faceLimit:1200,prompt:style+'Miniature frozen cave landmark: three broad ice-blue ice peaks with thick white snow caps on a small flat frosty blue base. Very chunky large angular shapes, no transparency, no icicles or tiny details.'},
 'portal-volcanic':{faceLimit:1400,prompt:style+'Miniature lava cave landmark: three chunky dark charcoal basalt towers split by broad vivid orange painted lava stripes, on a small flat dark foot. A large orange crystal at the centre. No particles, no thin spikes.'},
 'portal-fossil':{faceLimit:1600,prompt:style+'Miniature fossil cave landmark: an oversized ivory dinosaur skull and two broad curved ribs embedded into a chunky ochre stone pedestal. Friendly toy proportions, simplified large bones, broad silhouette, no teeth detail, no realism.'},
 'portal-machinery':{faceLimit:1600,prompt:style+'Miniature ancient machine landmark: one large thick bronze gear leaning against a chunky square dark stone frame, one big glowing-looking turquoise diamond at centre. Small flat base, simple oversized gear teeth, no wires or small gears.'},
 'portal-core':{faceLimit:1200,prompt:style+'Miniature earth core landmark: one massive gold diamond crystal between two broad dark purple blocky pillars, on a small flat purple stone base. Broad glossy-looking painted gold faces, no tiny crystals or effects.'},
 'egg-meadow':{faceLimit:900,prompt:style+'One large toy pet egg on a low blue square pedestal with cream beveled rim. A round white egg with exactly five large bright green spots, centred upright. Egg clearly dominates the compact base. Symmetric, solid smooth shapes, no faces, no animals.'},
 'egg-crystal':{faceLimit:900,prompt:style+'One large toy pet egg on a low purple square pedestal with cream beveled rim. A round pale blue egg with exactly five large purple diamond patches, centred upright. Egg clearly dominates the compact base. Symmetric, solid smooth shapes, no faces, no animals.'},
 'egg-ember':{faceLimit:900,prompt:style+'One large toy pet egg on a low orange square pedestal with cream beveled rim. A round warm yellow egg with exactly five large red flame-shaped patches, centred upright. Egg clearly dominates the compact base. Symmetric, solid smooth shapes, no faces, no animals.'},
};
